### ISSUE TITLE
Feature: Support free-text assignment

### ISSUE THREAD

**Issue by koppor** [takanome-dev/assign-issue-action#246]
### Type of feature

💡 Feature

### Current behavior

Students comment with

> Hello, could you please assign this issue to me? Keen to have a go.

> Hello, I am here to do a university assignment where I attempt to solve issues in open source projects! I would like to work on this issue, and am wondering if it is still available to do.

> Hi [...], my and my group members hope to contribute to this issue. Thx!

> Hi, I was wondering if this issue still needs to be worked on. If so, I would be happy to pick it up!

> I have read through this issue and was wondering if it is still available to take on. 

> Hi! May I work on this issue? I'm new here, thank you!

> Hey! May I work on this issue? thank you!

> I want to take this issue.

or other texts.

Currently, the action does not support this.

### Suggested solution

Ideas:

1. Support text and "contained-in". In this case, I configure "assign this issue to me" as text to recognize
2. Support OpenAI API to use an LLM to evaluate if text is an "assign-me" wish: IN: text OUT: "yes" or "no".

In case the LLM approach is used, there should be no comment and action if the issue is already taken. (To avoid errors)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
> Support text and "contained-in". In this case, I configure "assign this issue to me" as text to recognize

Interesting, this should be easy to implement 👍 

As for the LLM approach, might be something I will explore in the future (or if I have more time and credits 😄)

**Comment by koppor** [comment]
> > Support text and "contained-in". In this case, I configure "assign this issue to me" as text to recognize
> 
> Interesting, this should be easy to implement 👍

Nice! Maybe, I just collect all sentences indicating an assignment. However, the last days, they were all different 🙈.

**Comment by takanome-dev** [comment]
> the last days, they were all different 🙈.

😄 Feel free to post as many examples as you'd like! I can feed them into ChatGPT to help identify common patterns for recognizing assignment requests.

I was also considering adding an automatic greeting message when an issue is created, listing all available commands (e.g., `/assign-me`, `/unassign-me`). This feature could be toggled on/off in the configuration settings.

Not sure yet if that might be useful

**Comment by koppor** [comment]
> > the last days, they were all different 🙈.
> 
> 😄 Feel free to post as many examples as you'd like! I can feed them into ChatGPT to help identify common patterns for recognizing assignment requests.

I think, there needs to be a single prompt, which is then sent to the API. -- The users of the action need to configure their API key though.

> I was also considering adding an automatic greeting message when an issue is created, listing all available commands (e.g., `/assign-me`, `/unassign-me`). This feature could be toggled on/off in the configuration settings.

Since this is configurable (`assigned_comment`), I think, its good to add `/unassign-me` as hint. The others I would not post. Just listing in the `README.md` is enough. -- Mostly, the maintainers need it and they should not be remined on each usage of the action :)

**Comment by takanome-dev** [comment]
> I think, there needs to be a single prompt, which is then sent to the API. -- The users of the action need to configure their API key though.

What if the action automatically comments with available assignment commands when someone shows interest in contributing?
People often skip the docs and go straight to the issues. So, if they comment something like "assign this to me," the action could respond with:
"Hey @<user>, if you'd like to take on this issue, please use this command: /assign-me."

I can enable this feature by default, but you can choose to disable it in the config file if you prefer.

**Comment by koppor** [comment]
> I can enable this feature by default, but you can choose to disable it in the config file if you prefer.

Yeah, this makes it more transparent and avoids errors. - It fills up the notifications of people, because they then get four messages, but I think, this is acceptable.
